# Generated by Django 4.1 on 2023-01-23 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_complemento'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='CNPJ',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='telefone',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='whatsapp',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='loja',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Loja',
        ),
    ]
