# Generated by Django 4.1 on 2023-01-30 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_cliente_numero_casa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='numero_Casa',
            field=models.IntegerField(null=True),
        ),
    ]
